nataliarossini/The-Good-Dev

- Gemfile.lock
- config/routes.rb
Hi, I have attempted to create routes based on our google doc
> Routes as in our google doc

- app/models/organization.rb
- app/models/project.rb
- app/models/user.rb
- db/migrate/20210608132114_rename_organization_type_to_category.rb
- db/migrate/20210608133325_remove_user_id_from_projects.rb
- db/schema.rb
- db/seeds.rb
seed is done and I have to make a few adjustments to make it work
> seeded and adjusted a few models

- app/models/application.rb
- app/models/project.rb
- app/models/user.rb
- db/migrate/20210608151533_add_default_to_status.rb
- db/schema.rb
also added default value to status in the applications table
> added validation and association to user, application, project

- app/controllers/applications_controller.rb
- app/controllers/my_skills_controller.rb
- app/controllers/organizations_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/reviews_controller.rb
- app/controllers/users_controller.rb
- test/controllers/applications_controller_test.rb
- test/controllers/my_skills_controller_test.rb
- test/controllers/organizations_controller_test.rb
- test/controllers/projects_controller_test.rb
- test/controllers/reviews_controller_test.rb
- test/controllers/users_controller_test.rb
> created controllers

- app/controllers/my_skills_controller.rb
- app/controllers/users_controller.rb
- app/views/users/dashboard.html.erb
- config/routes.rb
Hi guys, could you please check my code?
> my skills action created a user dashboard

- app/controllers/users_controller.rb
- app/views/users/dashboard.html.erb
now dashboard only display skills selector for volunteers
> add if to dashboard skills

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/projects_controller.rb
- app/views/projects/index.html.erb
Please have a look and merge if you are happy with
> Brought the index page styling to what we have in figma

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/pages_controller.rb
- app/controllers/projects_controller.rb
- app/views/pages/home.html.erb
- app/views/projects/index.html.erb
> Styling home

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_new.scss
- app/views/devise/registrations/_organization.html.erb
- app/views/devise/registrations/_volunteer.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/organizations/new.html.erb
- app/views/projects/index.html.erb
I have styled the registration and log in forms, and did the conditional sourcing of project photo on index page
> Form and project picture

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_new.scss
- app/models/review.rb
- app/views/projects/index.html.erb
changed font to lighter version
> Profile css

- app/assets/stylesheets/pages/_project_show.scss
- app/views/projects/show.html.erb
Reverts nataliarossini/The-Good-Dev#52
> Revert "Revert "Profile css""

- app/assets/stylesheets/components/_navbar.scss
- app/javascript/components/navbar.js
- app/javascript/packs/application.js
- app/views/shared/_navbar.html.erb
added js to the navbar so it changes to white when you scroll
> JS on navbar when scrolling

- app/assets/stylesheets/application.scss
- app/javascript/components/navbar.js
added padding to the top so the navbar dont overlap
> fixed overlapping

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_chatroom.scss
- app/controllers/application_controller.rb
- app/controllers/chatrooms_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/users_controller.rb
- app/javascript/channels/chatroom_channel.js
- app/javascript/components/navbar.js
- app/javascript/components/status.js
- app/javascript/packs/application.js
- app/models/chatroom.rb
- app/models/user.rb
- app/views/chatrooms/index.html.erb
- app/views/chatrooms/show.html.erb
- app/views/messages/_message.html.erb
- app/views/projects/show.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/dashboard.html.erb
- config/routes.rb
- db/migrate/20210614111358_add_read_to_messages.rb
- db/migrate/20210614112336_add_users_to_chatrooms.rb
- db/schema.rb
asa I explained in the zoom call
> chat and a few additions to dashboard

- app/assets/config/manifest.js
- app/assets/stylesheets/pages/_dashboard.scss
- config/application.rb
- db/schema.rb
hopefully will work now 
i first ran :
`rake assets:precompile RAILS_ENV=production`
then it compiled everything, to undo that i ran:
`rails assets:clobber`
> trued to fix issue

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_buttons.scss
- app/controllers/projects_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_autocomplete.js
- app/javascript/plugins/init_mapbox.js
- app/models/project.rb
- app/models/skill.rb
- app/models/user.rb
- app/views/projects/index.html.erb
- package.json
- yarn.lock
hey guys the filter/search for projects are done
> search gem + filter in index page

- app/views/projects/show.html.erb
Just noticed we couldn't handle when project has multiple photos so I added carousel
> add carousel to multiple photos

- app/assets/stylesheets/pages/_chatroom.scss
- app/views/chatrooms/show.html.erb
- app/views/users/dashboard.html.erb
fixed chat input in the bottom and styled the input also just added a # to saved projects
> fixed chat input

- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/users/dashboard.html.erb
Reverts nataliarossini/The-Good-Dev#107
> Revert "added news on the dashboard and added style"

- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/users/dashboard.html.erb
Reverts nataliarossini/The-Good-Dev#108
> Revert "Revert "added news on the dashboard and added style""

- app/assets/stylesheets/pages/_chatroom.scss
- app/controllers/chatrooms_controller.rb
- app/javascript/channels/chatroom_channel.js
- app/javascript/packs/application.js
- app/views/chatrooms/show.html.erb
> fixed js errors

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/users/dashboard.html.erb
> added the edit and delete btns on the project dash. will work on placement later

- app/views/projects/edit.html.erb
I noticed the edit project form wasn't styled so I just applied the class like the others
> added form class to edit

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_profile.scss
- app/javascript/packs/application.js
- app/javascript/plugins/init_star_rating.js
- app/views/pages/home.html.erb
- app/views/projects/edit.html.erb
- app/views/projects/show.html.erb
- app/views/reviews/new.html.erb
- app/views/users/_organization.html.erb
- package.json
- yarn.lock
changes suggested by TAs we've done together and rating stars
> stars and small fix
